services:
  db:
    image: mariadb:10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=typo3-v14
      - MYSQL_USER=typo3
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
    restart: unless-stopped
  main:
    build: .
    image: csidirop/typo3-v14:14.3
    ports:
      - "127.0.0.1:80:80"
    environment:
      - DB_ADDR=db
      - DB_PORT=3306
    #volumes:
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
